delay = 60
changerate = 0.0087
downloadphotos = false
message = """
{{.Title}}
Price: ¥{{.PriceY}} (${{.PriceCurrency}}) - Buy Now: ¥{{.BuyNowPriceY}} (${{.BuyNowPriceCurrency}})
Until: {{.Endtime}} - Seller: {{.SellerID}}
{{.URL}}
"""

[[searches]]
url = "your url here"

[[searches]]
url = "your url here"